name: cv
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - aiohttp=3.6.2
  - async-timeout=3.0.1
  - attrs=19.3.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - chardet=3.0.4
  - cpuonly=1.0
  - idna=2.10
  - idna_ssl=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libdb=6.1.26
  - libffi=3.2.1
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - multidict=4.7.5
  - numpy=1.18.5
  - openssl=1.1.1g
  - portaudio=19.6.0
  - pyaudio=0.2.11
  - python=3.6.10
  - python-engineio=3.11.2
  - python-socketio=4.5.1
  - python_abi=3.6
  - pytorch=1.6.0
  - pyyaml=5.3.1
  - setuptools=49.1.0
  - six=1.15.0
  - speechrecognition=3.6.3
  - sqlite=3.32.3
  - tinydb=4.1.1
  - torchvision=0.7.0
  - tk=8.6.10
  - typing_extensions=3.7.4.2
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.4.2
  - zlib=1.2.11
  - pip:
    - beautifulsoup4==4.9.1
    - click==7.1.2
    - intel-openmp==2019.0
    - gtts==2.1.1
    - gtts-token==1.1.3
    - pip==20.1.1
    - pyttsx3==2.90
    - requests==2.24.0
    - soupsieve==2.0.1
    - transformers==3.0.2
    - urllib3==1.25.9
    - webrtcvad==2.0.10
prefix: /home/ivanvladimir/miniconda3/envs/cv

